name: haskell-practice
version: 0.1.0.0
license: BSD3
author: Dainslef
maintainer: dainslef@outlook.com
copyright: 2019 @ Dainslef
category: Web
build-type: Simple

# executables:
#   main:
#     source-dirs: app
#     main: Main.hs
#     dependencies:
#       - base
#       - haskell-practice
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
# library:
#   source-dirs: src
#   exposed-modules: Lib
#   dependencies: [base]

library:
  source-dirs: src
  dependencies: [base, stm, async, http-conduit, http-client, HUnit]

executables:
  main-test:
    source-dirs: test
    main: Test.hs
    dependencies: [base, hspec, stm, async, http-conduit, http-client, haskell-practice]
    other-modules: []
