name: haskell-practice
version: 0.1.0.0
license: BSD3
author: Dainslef
maintainer: dainslef@outlook.com
copyright: 2019 @ Dainslef
category: Web
build-type: Simple

executables:
  main:
    source-dirs: app
    main: Main.hs
    dependencies:
      - base
      - haskell-practice
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: src
  exposed-modules: Lib
  dependencies: [base]

tests:
  cps:
    source-dirs: test
    main: TestCSP.hs
    dependencies: [base]
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    other-modules: []
  type-class:
    source-dirs: test
    main: TestTypeClass.hs
    other-modules: []
    dependencies: [base]
  gadt:
    source-dirs: test
    main: TestGADT.hs
    dependencies: [base]
    other-modules: []
  pointfree:
    source-dirs: test
    main: TestPointfree.hs
    dependencies: [base]
    other-modules: []
  rankn:
    source-dirs: test
    main: TestGADT.hs
    dependencies: [base]
    other-modules: []
  http:
    source-dirs: test
    main: TestHTTP.hs
    dependencies: [base, http-conduit, http-client]
    other-modules: []
  monad:
    source-dirs: test
    main: TestMonad.hs
    dependencies: [base]
    other-modules: []
  async:
    source-dirs: test
    main: TestAsync.hs
    other-modules: []
    dependencies: [base, async]
  record:
    source-dirs: test
    main: TestDuplicateRecordFields.hs
    other-modules: []
    dependencies: [base]
  stm:
    source-dirs: test
    main: TestSTM.hs
    other-modules: []
    dependencies: [base, stm, async]
  tvar:
    source-dirs: test
    main: TestTVar.hs
    other-modules: []
    dependencies: [base, stm, async]
  tchan:
    source-dirs: test
    main: TestTChan.hs
    other-modules: []
    dependencies: [base, stm, async]
  y:
    source-dirs: test
    main: Y.hs
    other-modules: []
    dependencies: [base]
  exception:
    source-dirs: test
    main: TestException.hs
    other-modules: []
    dependencies: [base]
  lazy:
    source-dirs: test
    main: TestLazy.hs
    other-modules: []
    dependencies: [base]
