name: haskell-practice
version: 0.1.0.0
license: BSD3
author: Dainslef
maintainer: dainslef@outlook.com
copyright: 2019 @ Dainslef
category: Web
build-type: Simple

# executables:
#   main:
#     source-dirs: app
#     main: Main.hs
#     dependencies:
#       - base
#       - haskell-practice
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
# library:
#   source-dirs: src
#   exposed-modules: Lib
#   dependencies: [base]

library:
  source-dirs: src
  dependencies: [base, containers, stm, async, http-conduit, http-client, hspec]

tests:
  code-wars:
    source-dirs: test
    main: CodeWars.hs
    dependencies: [base, hspec, haskell-practice]
    other-modules: []
  lang-feature:
    source-dirs: test
    main: LangFeature.hs
    dependencies: [base, hspec, haskell-practice]
    other-modules: []
  hacker-rank:
    source-dirs: test
    main:  HackerRank.hs
    dependencies: [base, hspec, haskell-practice]
    other-modules: []
